tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: BI_ADMIN
      database: TASTY_BYTES_DBT_DB_YPR
      schema: dev
      warehouse: WH_XS
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: BI_ADMIN
      database: TASTY_BYTES_DBT_DB_YPR
      schema: prod
      warehouse: WH_XS